# Generated by Django 4.2.6 on 2023-11-17 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_likes_posts_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='users',
        ),
        migrations.AddField(
            model_name='likes',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userlikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
