# Generated by Django 4.2.6 on 2023-11-02 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_posts_likes_followers_user_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='liked',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='network.likes'),
        ),
    ]
