# Generated by Django 4.2.6 on 2023-10-26 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 13, 39, 57, 360866)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 13, 39, 57, 361302)),
        ),
        migrations.AlterField(
            model_name='listings',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 13, 39, 57, 360367)),
        ),
    ]
