# Generated by Django 4.2.6 on 2023-10-24 14:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=200)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.listings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(datetime.datetime, models.Model),
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Automotive', 'Automotive'), ('Beauty', 'Beauty'), ('BabyProducts', 'Baby Products'), ('Books', 'Books'), ('Camera', 'Camera'), ('CellPhones', 'Cell Phones'), ('Eletronics', 'Eletronics'), ('FineArt', 'Fine Art'), ('Foods', 'Foods'), ('HealthCare', 'Health Care'), ('Home', 'Home'), ('Music', 'Music'), ('Ofice', 'Ofice'), ('Outdoors', 'Outdoors'), ('Sports', 'Sports'), ('Toys', 'Toys'), ('Video', 'Video'), ('VideoGames', 'Video Games')], max_length=64)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='auctions.listings')),
            ],
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.listings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bids', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(datetime.datetime, models.Model),
        ),
    ]
