# Generated by Django 4.2.6 on 2023-12-06 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_bids_time_alter_comments_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 12, 51, 22, 149136)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 12, 51, 22, 149457)),
        ),
        migrations.AlterField(
            model_name='listings',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='listings',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 12, 51, 22, 148639)),
        ),
    ]
